### PR TITLE
Change size_t and friends to use `long` types.

### PR DESCRIPTION
**Pull request by sunfishcode**
This change accompanies https://github.com/kripken/emscripten/pull/5916.

### CODE REVIEW

**Comment by juj** [comment]
lgtm, before merging, let's coordinate this to bump version to `1.38.0` since this had a detected ABI signature change.

**Comment by sunfishcode** [comment]
[The LLVM patch](https://reviews.llvm.org/D40526), [the emscripten-fastcomp-clang patch](https://github.com/kripken/emscripten-fastcomp-clang/pull/21), and [the emscripten patch](https://github.com/kripken/emscripten/pull/5916) are now all updated and in sync.

I've taken this opportunity to update emscripten-fastcomp-clang to some of the newer C++ ABI settings, while here.

**Comment by sunfishcode** [comment]
I've now rebased the patches on top of the recent upstream merge, and I bumped the version to 1.38.0.

**Comment by kripken** [comment]
There is discussion in progress in #6174 about what a version change to 1.38.0 should entail.

**Comment by sunfishcode** [comment]
I've now rebased the patches to latest incoming, and I bumped the version to 1.39.0.

**Comment by sunfishcode** [comment]
https://github.com/kripken/emscripten/pull/5916 is now merged, merging the corresponding emscripten-fastcomp-clang patch.

**Pull request merged**
