### PR TITLE
Update to LLVM 4.0

### PR DESCRIPTION
**Pull request by dylanmckay**
This is accompanied with kripken/emscripten-fastcomp#165

### CODE REVIEW

**Comment by kripken** [comment]
Nice, thanks! :)

What's the status of this and the second PR? (WIP I guess from the title, but I'm curious for more detail, if it's not too early)

**Comment by dylanmckay** [comment]
> Nice, thanks! :)

No problem :)

They're both mostly done. I've merged 4.0 into both of them, resolved all conflicts, audited the diff against 4.0 and everything looks good.

I haven't run the `clang` test suite yet, but I imagine it will likely pass once the two above `CodeGen` tests pass.

**Comment by kripken** [comment]
Great!

We don't actually run the clang test suite ourselves, since we hardly modified clang - it should just pass, yeah. What is more crucial to test is the emscripten test suite - often a merge hits issues there. Let me know if I can help with testing/fixing stuff there.

We'll need to bump the emscripten expected LLVM version number (in tools/shared.py in the emscripten repo), so we'll need a small PR to emscripten to do that, and to handle any test fixes/changes if any. I can help there too if you want.

**Comment by dylanmckay** [comment]
Superseded by #14

**Pull request closed without merging**
