### PR TITLE
fix optimization of struct returns when there is a constructor, updat…

### PR DESCRIPTION
**Pull request by kripken**
…e ABI code to match wasm's which we are following. They had a bug, and fixed it apparently.

Once we merge the targets, stuff like this would never happen.

### CODE REVIEW

**Comment by kripken** [comment]
Hmm, this doesn't work right, it fails e.g. `test_std_cout_new`.

I tried copying the adjoining wasm ABI logic in `classifyArgumentType` as well (thinking they might need to 'match'), but that doesn't help either. So there is some more complex issue with how the asm.js ABI differs from wasm. I don't know much about the C++ ABI, so if someone can help that would be great.

**Comment by kripken** [comment]
(Similarly, just removing the optimization will break that same test, and others.)

**Comment by labsin** [comment]
I had the same breaking test (only tested this one). Removing the cache after rebuilding clang (I rebuild clang manually, without the sdk) fixes it for me in my pull-request.

**Comment by kripken** [comment]
Oh wow, you're totally right. I didn't think about that, but yeah, makes sense we need to rebuild libraries for a change like this. I'll run some more tests to be totally sure, then merge with a version bump.

**Pull request merged**
